---
save_checkpoints: true
checkpoint_name: segmentation_baseline.pth
checkpoint_dir: /.../path/to/checkpoints
plot_dir: /.../path/to/output
data_dir: /.../path/to/data
seed: 1234

architecture: deeplabv3plus
encoder_name: efficientnet-b2
encoder_weights: imagenet
use_batchnorm: true
pooling: avg
dropout: 0.4
device: cuda
workers: 4

loss: dice_loss
loss_weight: 0.8
combine: false
metrics:
  - name: dice_score
    type: segmentation
  - name: dice_loss
    type: segmentation
  - name: dice_score
    type: segmentation
  - name: cross_entropy
    type: classification
  - name: accuracy
    type: classification
rounding: 0.5
ignore_channels: null

lr: 5.0e-4
epochs: 75
batch_size: 40
optimizer: adam
scheduler: cosine
max_round: 75
eta_min: 1.0e-6
step_size: 15
gamma: 0.5

spacing: 4.0
patch_size_train: 320
patch_size_valid: 320
verbose: true
normalize: simple
transform: artifact
eval_dir: /.../path/to/transform
ink_filters: null

classes: 
  - Tissue folds
  - Ink
  - Air bubbles
  - Dust
  - Marker
  - Out-of-focus

spacing: 2.0
tolerance: 0.25
patch_size: 256
overlap: 32
minimum: 0.03125
balance: null
verbose: true


train_data: /.../path/to/data_train.csv
valid_data: /.../path/to/data_valid.csv
test_data: /.../path/to/data_test.csv